name: Laravel Backend CI/CD

on:
  push:
    branches:
      - dev_wfh
      - main  # Also trigger on pushes to main
    paths:
      - 'backend-api/**'

  pull_request:
    branches:
      - dev_wfh
      - main  # Also trigger on pull requests to main
    paths:
      - 'backend-api/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Copy .env and .env.testing
      working-directory: backend-api
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php -r "file_exists('.env.testing') || copy('.env.example', '.env.testing');"

    - name: Run Composer Install
      working-directory: backend-api
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Generate Application Key
      working-directory: backend-api
      run: php artisan key:generate

    - name: Run Laravel Tests
      working-directory: backend-api
      env:
        APP_ENV: testing
        DB_CONNECTION: pgsql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 5432
        DB_DATABASE: test_db
        DB_USERNAME: postgres
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: php artisan test

  deploy:
    needs: laravel-tests  # Deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH Access
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy Files to EC2
      run: |
        scp -r ./backend-api ec2-user@54.251.20.155:/var/www/html/spm-project/backend-api

    - name: Run Laravel Commands on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.251.20.155 << 'EOF'
        cd /var/www/html/spm-project/backend-api
        if [ -f composer.lock ]; then
          composer install --no-dev --optimize-autoloader
        fi
        php artisan migrate --force
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        sudo chmod -R 775 storage bootstrap/cache
        sudo chown -R apache:apache /var/www/html/spm-project/backend-api
        export APP_ENV=production
        sudo systemctl restart httpd
        EOF
